# Default values for pm_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bmceniery/md_service
  tag: 1.8
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "md-service"
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

configmap:
  namespace: md-service


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 6
    memory: 24576Mi
  requests:
    cpu: 4
    memory: 12288Mi

nodeSelector: {}

tolerations: []

affinity: {}
