apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "md_chart.fullname" . }}-configmap
  namespace: {{ .Values.configmap.namespace }}

data:
  camera.ip: {{ .Values.configmap.camera.ip }}
  camera.port: {{ .Values.configmap.camera.port }}
