apiVersion: v1
kind: Service
metadata:
  name: {{ include "md_chart.fullname" . }}
  labels:
{{ include "md_chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - port: 5000
      targetPort: 5000
      protocol: UDP
  selector:
    app/name: {{ include "md_chart.name" . }}
    app/instance: {{ .Release.Name }}
  externalIPs:
    - {{ .Values.service.externalIP }}
